<?php

/**
 * @file
 * Primary module hooks for Puffin Layouts module.
 */

/**
 * Implements hook_theme().
 */
function puffin_layouts_theme($existing, $type, $theme, $path) {
  return [
    'paragraph' => [
      'render element' => 'elements',
    ],
    'paragraph__flip_card' => [
      'template' => 'paragraph--flip-card',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_page()
 */
function puffin_layouts_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'puffin/global-styling';
}
