<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for Puffin Layouts module.
 */

/**
 * Implements hook_theme().
 */
function puffin_layouts_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__quote' => [
      'template' => 'paragraph--quote',
      'base hook' => 'paragraph',
    ],
    'paragraph__hero_100vw' => [
      'template' => 'paragraph--hero-100vw',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implement hook_theme_registry_alter()
 */
function puffin_layouts_theme_registry_alter(&$theme_registry) {
  $theme_registry['paragraph']['template'] = 'paragraph';
  $theme_registry['paragraph']['path'] = \Drupal::service('extension.list.module')->getPath('puffin_layouts') . '/templates';
}

function puffin_layouts_form_views_form_media_library_widget_image_alter(array &$form, FormStateInterface $form_state) {

  //Add classes to media library form
  $form['#attributes']['class'][] = 'd-flex';
  $form['#attributes']['class'][] = 'flex-wrap';
  $form['#attributes']['class'][] = 'gap-2';
}
