<?php

/**
 * @file
 * Primary module hooks for Puffin Layouts module.
 */

/**
 * Implements hook_theme().
 */
function puffin_layouts_theme($existing, $type, $theme, $path) {
  return [
    'paragraph' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implement hook_theme_registry_alter()
 */
function puffin_layouts_theme_registry_alter(&$theme_registry) {
  $theme_registry['paragraph']['template'] = 'paragraph';
  $theme_registry['paragraph']['path'] = \Drupal::service('extension.list.module')->getPath('puffin_layouts') . '/templates';
}

/**
 * Implements hook_preprocess_page()
 */
function puffin_layouts_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'puffin/bootstrap';
}
